name: Glog.AI Scan

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  security-events: write
  issues: write

jobs:
  glog-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkout glog-action
        uses: actions/checkout@v4
        with:
          repository: glogai/glog-action
          token: ${{ secrets.PAT_TOKEN }}
          path: .github/actions/glog-action
          ref: main

      - name: Run Glog.AI scan
        uses: ./.github/actions/glog-action
        with:
          lang: python,javascript
          client: test
          env: dev
          upload: true
          issue: false
          autofix: false
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
