name: Glog.AI Scan

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read
  security-events: write
  issues: write

jobs:
  glog-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Glog.AI scan
        uses: glogai/glog-action@main
        with:
          path: .
          lang: python,javascript
          client: test
          env: dev
          upload: true
          issue: false
          autofix: false
          github-token: ${{ secrets.PAT_TOKEN }}
          glog-token: ${{ secrets.GLOG_TOKEN }}
